# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mdetect-gnn',
                'doc_host': 'https://khannay.github.io',
                'git_url': 'https://github.com/khannay/mdetect-gnn',
                'lib_path': 'mdetect_gnn'},
  'syms': {'mdetect_gnn.core': {'mdetect_gnn.core.foo': ('core.html#foo', 'mdetect_gnn/core.py')}}}
